/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package voyagefinancial;

import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TannerLuke
 */
public class FinancialAssets extends javax.swing.JPanel {

    
    UserInterface ui;
    ClientProfile clientInfo;
    ClientProfile spouseInfo;
    private boolean hasSpouseInfo = false;
    
    ArrayList<Integer> editableRows = new ArrayList<Integer>();
    ArrayList <String> coloredCells = new ArrayList<String>();
    
    /**
     * Creates new form FinancialAssets
     */
    public FinancialAssets() {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        clientDataTable = new javax.swing.JTable();
        wageInfoButton = new javax.swing.JButton();
        contributionInfoButton = new javax.swing.JButton();
        rothInfoButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        spouseDataTable = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 164, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clientDataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(clientDataTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 5, 960, 470));

        wageInfoButton.setText("jButton1");
        wageInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wageInfoButtonActionPerformed(evt);
            }
        });
        jPanel1.add(wageInfoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 50, -1));

        contributionInfoButton.setText("jButton2");
        contributionInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contributionInfoButtonActionPerformed(evt);
            }
        });
        jPanel1.add(contributionInfoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 40, -1));

        rothInfoButton.setText("jButton2");
        rothInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rothInfoButtonActionPerformed(evt);
            }
        });
        jPanel1.add(rothInfoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 40, -1));

        jTabbedPane2.addTab("tab3", jPanel1);

        spouseDataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(spouseDataTable);

        jTabbedPane2.addTab("tab2", jScrollPane2);

        add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 1028, 520));
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void tryToGetSpouse() {
        if (ui.getSpouseProfile() != null) {
            spouseInfo = ui.getSpouseProfile();
            hasSpouseInfo = true;
            
        } else {
            jTabbedPane1.removeTabAt(1);
        }
    }
    
    public final void createClientTable() {
        
        int currentYear = Calendar.getInstance().get(Calendar.YEAR);
        Object yearArray[] = new Object[20];
        yearArray[0] = "";
        for (int i = 1; i < 20; i++) {
            yearArray[i] = currentYear + i - 1;
            
        }
        Object[][] nameArray = {
            {"Age"}
            
            
        };
        
        clientDataTable.setDefaultRenderer(Object.class, new DefaultTableCellRenderer(){
            @Override
            public Component getTableCellRendererComponent(JTable table,
                Object value, boolean isSelected, boolean hasFocus, int row, int col) {

                super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, col);
                
                
                
                //String status = (String)table.getModel().getValueAt(row, STATUS_COL);
                String val = (String) table.getModel().getValueAt(row, 0);
                
                
                
                if (coloredCells.contains(val)) {
                    setBackground(Color.LIGHT_GRAY);
                    setForeground(Color.WHITE);
                    
                
                } else {
                    setBackground(table.getBackground());
                    setForeground(table.getForeground());
                }  
                
                return this;
            }
        });
        
        DefaultTableModel model = new DefaultTableModel(nameArray, yearArray) {
       // MyTableModel model = new MyTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return editableRows.contains(row);
            }
        };
        clientDataTable.setModel(model);
        
        clientDataTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
        for (int i = 1; i < 20; i++) {
            int age = clientInfo.getAge() + i - 1;
            clientDataTable.setValueAt(age, 0, i);
        }
    
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    private void wageInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wageInfoButtonActionPerformed
        if (clientDataTable.getRowHeight(2) == 1) {
            int height = clientDataTable.getRowHeight(0);
            clientDataTable.setRowHeight(2, height);
            clientDataTable.setRowHeight(1, height);
        } else {
            clientDataTable.setRowHeight(1, 1);
            clientDataTable.setRowHeight(2,1);
        }
    }//GEN-LAST:event_wageInfoButtonActionPerformed

    private void contributionInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contributionInfoButtonActionPerformed
        if (clientDataTable.getRowHeight(4) == 1) {
            int height = clientDataTable.getRowHeight(0);
            clientDataTable.setRowHeight(4, height);
            clientDataTable.setRowHeight(5, height);
            clientDataTable.setRowHeight(6, height);
        } else {
            clientDataTable.setRowHeight(4, 1);
            clientDataTable.setRowHeight(5, 1);
            clientDataTable.setRowHeight(6, 1);
        }
    }//GEN-LAST:event_contributionInfoButtonActionPerformed

    private void rothInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rothInfoButtonActionPerformed
        if (clientDataTable.getRowHeight(8) == 1) {
            int height = clientDataTable.getRowHeight(0);
            clientDataTable.setRowHeight(8, height);
        } else {
            clientDataTable.setRowHeight(8, 1);
        }
    }//GEN-LAST:event_rothInfoButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable clientDataTable;
    private javax.swing.JButton contributionInfoButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton rothInfoButton;
    private javax.swing.JTable spouseDataTable;
    private javax.swing.JButton wageInfoButton;
    // End of variables declaration//GEN-END:variables
}
