/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package voyagefinancial;

import java.awt.Color;

/**
 *
 * @author TannerLuke
 */
public class PensionInfoPanel extends javax.swing.JPanel implements GettingJPanelInterface {

    /**
     * Creates new form PensionInfoPanel
     */
    private int amountPension;
    private boolean clientRecievesLumpSumBool; 
    private boolean clientRecievesMonthlyBool;
    private int costOfLivingAdjustment;
    private boolean extraPanel;
    private String panelName;
    
    private boolean belongsToClient;
    private boolean belongsToSpouse;
    
    
    private int month;
    private int day;
    private int year;
    
    
    
    
    public PensionInfoPanel() {
        initComponents();
        clientRecievesLumpSumBool = false;
        clientRecievesMonthlyBool = false;
        
    
        
        costOfLivingAdjustment = 0;
        panelName = "pension";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel141 = new javax.swing.JLabel();
        jLabel149 = new javax.swing.JLabel();
        clientRecievesLumpSum = new javax.swing.JRadioButton();
        clientRecievesLMonthly = new javax.swing.JRadioButton();
        amountText = new javax.swing.JTextField();
        jLabel234 = new javax.swing.JLabel();
        monthAsOf403b = new javax.swing.JTextField();
        jLabel235 = new javax.swing.JLabel();
        dayAsOf403b = new javax.swing.JTextField();
        jLabel236 = new javax.swing.JLabel();
        yearAsOf403b = new javax.swing.JTextField();
        AdjustmentPanel = new javax.swing.JPanel();
        Adjustment = new javax.swing.JPanel();
        jLabel150 = new javax.swing.JLabel();
        costOfLivingAdjustmentYes = new javax.swing.JRadioButton();
        costOfLivingAdjustmentNo = new javax.swing.JRadioButton();
        BothOrOnePanel = new javax.swing.JPanel();
        OnePanel = new javax.swing.JPanel();
        jLabel152 = new javax.swing.JLabel();
        additionalPanelsYes1 = new javax.swing.JRadioButton();
        additionalPanelsNo1 = new javax.swing.JRadioButton();
        jLabel237 = new javax.swing.JLabel();
        whoDoes403bBelongto = new javax.swing.JComboBox<>();
        BothPanel = new javax.swing.JPanel();
        jLabel151 = new javax.swing.JLabel();
        additionalPanelsYes = new javax.swing.JRadioButton();
        additionalPanelsNo = new javax.swing.JRadioButton();
        jLabel238 = new javax.swing.JLabel();
        whoDoesPensionBelongTo = new javax.swing.JComboBox<>();
        costOfLivingAdjustmentText = new javax.swing.JTextField();
        NoAdjustment = new javax.swing.JPanel();
        jLabel153 = new javax.swing.JLabel();
        additionalPanelsYes2 = new javax.swing.JRadioButton();
        additionalPanelsNo2 = new javax.swing.JRadioButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel141.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel141.setText("Pension");
        add(jLabel141, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 139, 40));

        jLabel149.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel149.setText("How do you plan to receive your Pension?");
        add(jLabel149, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, -1, 30));

        clientRecievesLumpSum.setText("Lump Sum");
        clientRecievesLumpSum.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                clientRecievesLumpSumStateChanged(evt);
            }
        });
        add(clientRecievesLumpSum, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, -1, 30));

        clientRecievesLMonthly.setText("Monthly");
        clientRecievesLMonthly.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                clientRecievesLMonthlyStateChanged(evt);
            }
        });
        add(clientRecievesLMonthly, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 140, -1, 30));

        amountText.setBackground(new java.awt.Color(204, 204, 204));
        amountText.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        amountText.setForeground(new java.awt.Color(102, 102, 102));
        amountText.setText("Amount");
        amountText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        amountText.setSelectedTextColor(new java.awt.Color(153, 153, 153));
        amountText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                amountTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                amountTextFocusLost(evt);
            }
        });
        add(amountText, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 250, 30));

        jLabel234.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel234.setText("Rollover Date:");
        add(jLabel234, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 90, 30));

        monthAsOf403b.setBackground(new java.awt.Color(204, 204, 204));
        monthAsOf403b.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        monthAsOf403b.setForeground(new java.awt.Color(102, 102, 102));
        monthAsOf403b.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        monthAsOf403b.setText("mm");
        monthAsOf403b.setBorder(null);
        monthAsOf403b.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                monthAsOf403bFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                monthAsOf403bFocusLost(evt);
            }
        });
        add(monthAsOf403b, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 210, 30, 30));

        jLabel235.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel235.setText(" / ");
        add(jLabel235, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 210, -1, 30));

        dayAsOf403b.setBackground(new java.awt.Color(204, 204, 204));
        dayAsOf403b.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        dayAsOf403b.setForeground(new java.awt.Color(102, 102, 102));
        dayAsOf403b.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dayAsOf403b.setText("dd");
        dayAsOf403b.setBorder(null);
        dayAsOf403b.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dayAsOf403bFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dayAsOf403bFocusLost(evt);
            }
        });
        add(dayAsOf403b, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 210, 30, 30));

        jLabel236.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel236.setText(" / ");
        add(jLabel236, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 210, -1, 30));

        yearAsOf403b.setBackground(new java.awt.Color(204, 204, 204));
        yearAsOf403b.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        yearAsOf403b.setForeground(new java.awt.Color(102, 102, 102));
        yearAsOf403b.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        yearAsOf403b.setText("yyyy");
        yearAsOf403b.setBorder(null);
        yearAsOf403b.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                yearAsOf403bFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                yearAsOf403bFocusLost(evt);
            }
        });
        add(yearAsOf403b, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 210, 60, 30));

        AdjustmentPanel.setLayout(new java.awt.CardLayout());

        Adjustment.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel150.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel150.setText("Is there a cost of living adjustment?");
        Adjustment.add(jLabel150, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        costOfLivingAdjustmentYes.setText("Yes");
        costOfLivingAdjustmentYes.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                costOfLivingAdjustmentYesStateChanged(evt);
            }
        });
        costOfLivingAdjustmentYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costOfLivingAdjustmentYesActionPerformed(evt);
            }
        });
        Adjustment.add(costOfLivingAdjustmentYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, 30));

        costOfLivingAdjustmentNo.setText("No");
        costOfLivingAdjustmentNo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                costOfLivingAdjustmentNoStateChanged(evt);
            }
        });
        costOfLivingAdjustmentNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costOfLivingAdjustmentNoActionPerformed(evt);
            }
        });
        Adjustment.add(costOfLivingAdjustmentNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, 30));

        BothOrOnePanel.setLayout(new java.awt.CardLayout());

        OnePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel152.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel152.setText("Any additional Pension Plans?");
        OnePanel.add(jLabel152, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, 30));

        additionalPanelsYes1.setText("Yes");
        additionalPanelsYes1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                additionalPanelsYes1StateChanged(evt);
            }
        });
        OnePanel.add(additionalPanelsYes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, 30));

        additionalPanelsNo1.setText("No");
        additionalPanelsNo1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                additionalPanelsNo1StateChanged(evt);
            }
        });
        OnePanel.add(additionalPanelsNo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, -1, 30));

        jLabel237.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel237.setText("Belongs to");
        OnePanel.add(jLabel237, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 70, 40));

        whoDoes403bBelongto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[Choose One]", "Client", "Spouse" }));
        whoDoes403bBelongto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whoDoes403bBelongtoActionPerformed(evt);
            }
        });
        OnePanel.add(whoDoes403bBelongto, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 160, 40));

        BothOrOnePanel.add(OnePanel, "card2");

        BothPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel151.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel151.setText("Any additional Pension Plans?");
        BothPanel.add(jLabel151, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 80, 180, 30));

        additionalPanelsYes.setText("Yes");
        additionalPanelsYes.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                additionalPanelsYesStateChanged(evt);
            }
        });
        BothPanel.add(additionalPanelsYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, 30));

        additionalPanelsNo.setText("No");
        additionalPanelsNo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                additionalPanelsNoStateChanged(evt);
            }
        });
        BothPanel.add(additionalPanelsNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, 30));

        jLabel238.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel238.setText("Belongs to");
        BothPanel.add(jLabel238, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, -1, 30));

        whoDoesPensionBelongTo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[Choose One]", "Client", "Spouse" }));
        whoDoesPensionBelongTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whoDoesPensionBelongToActionPerformed(evt);
            }
        });
        BothPanel.add(whoDoesPensionBelongTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 150, 30));

        costOfLivingAdjustmentText.setBackground(new java.awt.Color(204, 204, 204));
        costOfLivingAdjustmentText.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        costOfLivingAdjustmentText.setForeground(new java.awt.Color(102, 102, 102));
        costOfLivingAdjustmentText.setText("Cost of Living Adjustment");
        costOfLivingAdjustmentText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        costOfLivingAdjustmentText.setSelectedTextColor(new java.awt.Color(153, 153, 153));
        costOfLivingAdjustmentText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                costOfLivingAdjustmentTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                costOfLivingAdjustmentTextFocusLost(evt);
            }
        });
        BothPanel.add(costOfLivingAdjustmentText, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 450, 30));

        BothOrOnePanel.add(BothPanel, "card3");

        Adjustment.add(BothOrOnePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 50, 710, 130));

        AdjustmentPanel.add(Adjustment, "card3");

        NoAdjustment.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel153.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel153.setText("Any additional Pension Plans?");
        NoAdjustment.add(jLabel153, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, 30));

        additionalPanelsYes2.setText("Yes");
        additionalPanelsYes2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                additionalPanelsYes2StateChanged(evt);
            }
        });
        NoAdjustment.add(additionalPanelsYes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, 30));

        additionalPanelsNo2.setText("No");
        additionalPanelsNo2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                additionalPanelsNo2StateChanged(evt);
            }
        });
        NoAdjustment.add(additionalPanelsNo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, 30));

        AdjustmentPanel.add(NoAdjustment, "card2");

        add(AdjustmentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 620, 180));
    }// </editor-fold>//GEN-END:initComponents

    private void clientRecievesLumpSumStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_clientRecievesLumpSumStateChanged
        if (clientRecievesLumpSum.isSelected()) {
            clientRecievesLMonthly.setSelected(false);
            clientRecievesLumpSumBool = true;
            clientRecievesMonthlyBool = false;
            
            AdjustmentPanel.removeAll();
            AdjustmentPanel.add(NoAdjustment);
            AdjustmentPanel.repaint();
            AdjustmentPanel.revalidate();
        } 
    }//GEN-LAST:event_clientRecievesLumpSumStateChanged

    private void clientRecievesLMonthlyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_clientRecievesLMonthlyStateChanged
        if (clientRecievesLMonthly.isSelected()) {
            clientRecievesLumpSum.setSelected(false);
            clientRecievesMonthlyBool = true;
            clientRecievesLumpSumBool = false;
            
            AdjustmentPanel.removeAll();
            AdjustmentPanel.add(Adjustment);
            AdjustmentPanel.repaint();
            AdjustmentPanel.revalidate();
        }
    }//GEN-LAST:event_clientRecievesLMonthlyStateChanged

    private void costOfLivingAdjustmentYesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_costOfLivingAdjustmentYesStateChanged
        if (costOfLivingAdjustmentYes.isSelected()) {
            costOfLivingAdjustmentNo.setSelected(false);
            //costOfLivingAdjustmentText.setVisible(true);
            BothOrOnePanel.removeAll();
            BothOrOnePanel.add(BothPanel);
            BothOrOnePanel.repaint();
            BothOrOnePanel.revalidate();
        }
    }//GEN-LAST:event_costOfLivingAdjustmentYesStateChanged

    private void costOfLivingAdjustmentNoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_costOfLivingAdjustmentNoStateChanged
        if (costOfLivingAdjustmentNo.isSelected()) {
            costOfLivingAdjustmentYes.setSelected(false);
            //costOfLivingAdjustmentText.setVisible(false);
            BothOrOnePanel.removeAll();
            BothOrOnePanel.add(OnePanel);
            BothOrOnePanel.repaint();
            BothOrOnePanel.revalidate();

        }
    }//GEN-LAST:event_costOfLivingAdjustmentNoStateChanged

    private void amountTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_amountTextFocusGained
        if (amountText.getText().equals("Amount")) {
            amountText.setText("");
            amountText.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_amountTextFocusGained

    private void amountTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_amountTextFocusLost
        if (amountText.getText().equals("")) {
            amountText.setText("Amount");
            amountText.setForeground(Color.GRAY);
        } else {
            try {
                amountPension = Integer.parseInt(amountText.getText());
            } catch (NumberFormatException e) {
                PopupMessage.popupMessage("Error", "Amount");
            }
        }
    }//GEN-LAST:event_amountTextFocusLost

    private void monthAsOf403bFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_monthAsOf403bFocusGained
        if (monthAsOf403b.getText().equals("mm")) {
            monthAsOf403b.setText("");
            monthAsOf403b.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_monthAsOf403bFocusGained

    private void monthAsOf403bFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_monthAsOf403bFocusLost
        if (monthAsOf403b.getText().equals("")) {
            monthAsOf403b.setText("mm");
            monthAsOf403b.setForeground(Color.GRAY);
        } else {
            try {
                month = Integer.parseInt(monthAsOf403b.getText());
            } catch (NumberFormatException e) {
                PopupMessage.popupMessage("Error", "Month");
            }
        }
    }//GEN-LAST:event_monthAsOf403bFocusLost

    private void dayAsOf403bFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dayAsOf403bFocusGained
        if (dayAsOf403b.getText().equals("dd")) {
            dayAsOf403b.setText("");
            dayAsOf403b.setForeground(Color.BLACK);
        } 
    }//GEN-LAST:event_dayAsOf403bFocusGained

    private void dayAsOf403bFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dayAsOf403bFocusLost
        if (dayAsOf403b.getText().equals("")) {
            dayAsOf403b.setText("dd");
            dayAsOf403b.setForeground(Color.GRAY);
        } else {
            try {
                day = Integer.parseInt(dayAsOf403b.getText());
            } catch (NumberFormatException e) {
                PopupMessage.popupMessage("Error", "Day");
            }
        }
    }//GEN-LAST:event_dayAsOf403bFocusLost

    private void yearAsOf403bFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_yearAsOf403bFocusGained
        if (yearAsOf403b.getText().equals("yyyy")) {
            yearAsOf403b.setText("");
            yearAsOf403b.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_yearAsOf403bFocusGained

    private void yearAsOf403bFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_yearAsOf403bFocusLost
        if (yearAsOf403b.getText().equals("")) {
            yearAsOf403b.setText("yyyy");
            yearAsOf403b.setForeground(Color.GRAY);
        } else {
            try {
                year = Integer.parseInt(yearAsOf403b.getText());
            } catch (NumberFormatException e) {
                PopupMessage.popupMessage("Error", "Year");
            }
        }
    }//GEN-LAST:event_yearAsOf403bFocusLost

    private void additionalPanelsYesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_additionalPanelsYesStateChanged
        if (additionalPanelsYes.isSelected()) {
            additionalPanelsNo.setSelected(false);
            additionalPanelsNo1.setSelected(false);
            additionalPanelsNo2.setSelected(false);
            additionalPanelsYes1.setSelected(true);
            additionalPanelsYes2.setSelected(true);
            extraPanel = true;
            
        }
    }//GEN-LAST:event_additionalPanelsYesStateChanged

    private void additionalPanelsNoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_additionalPanelsNoStateChanged
        if (additionalPanelsNo.isSelected()) {
            additionalPanelsYes.setSelected(false);
            additionalPanelsYes1.setSelected(false);
            additionalPanelsYes2.setSelected(false);
            additionalPanelsNo1.setSelected(true);
            additionalPanelsNo2.setSelected(true);
            extraPanel = false;
            
        }
    }//GEN-LAST:event_additionalPanelsNoStateChanged

    private void additionalPanelsYes1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_additionalPanelsYes1StateChanged
        if (additionalPanelsYes1.isSelected()) {
            additionalPanelsNo1.setSelected(false);
            additionalPanelsNo.setSelected(false);
            additionalPanelsNo2.setSelected(false);
            additionalPanelsYes.setSelected(true);
            additionalPanelsYes2.setSelected(true);
            extraPanel = true;
        }
    }//GEN-LAST:event_additionalPanelsYes1StateChanged

    private void additionalPanelsNo1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_additionalPanelsNo1StateChanged
        if (additionalPanelsNo1.isSelected()) {
            additionalPanelsYes1.setSelected(false);
            additionalPanelsYes.setSelected(false);
            additionalPanelsYes2.setSelected(false);
            additionalPanelsNo.setSelected(true);
            additionalPanelsNo2.setSelected(true);
            extraPanel = false;
        }
    }//GEN-LAST:event_additionalPanelsNo1StateChanged

    private void additionalPanelsYes2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_additionalPanelsYes2StateChanged
        if (additionalPanelsYes2.isSelected()) {
            additionalPanelsNo2.setSelected(false);
            additionalPanelsNo.setSelected(false);
            additionalPanelsNo1.setSelected(false);
            additionalPanelsYes.setSelected(true);
            additionalPanelsYes1.setSelected(true);
            extraPanel = true;
        }
    }//GEN-LAST:event_additionalPanelsYes2StateChanged

    private void additionalPanelsNo2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_additionalPanelsNo2StateChanged
        if (additionalPanelsNo2.isSelected()) {
            additionalPanelsYes.setSelected(false);
            additionalPanelsYes1.setSelected(false);
            additionalPanelsYes2.setSelected(false);
            additionalPanelsNo1.setSelected(true);
            additionalPanelsNo.setSelected(true);
            extraPanel = false;
        }
    }//GEN-LAST:event_additionalPanelsNo2StateChanged

    private void whoDoesPensionBelongToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whoDoesPensionBelongToActionPerformed
        if (whoDoes403bBelongto.getSelectedItem().toString().equals("Client")) {
            belongsToClient = true;
            belongsToSpouse = false;
        } else if (whoDoes403bBelongto.getSelectedItem().toString().equals("Spouse")) {
            belongsToClient = false;
            belongsToSpouse = true;
        } else {
            belongsToClient = false;
            belongsToSpouse = false;
        }
    }//GEN-LAST:event_whoDoesPensionBelongToActionPerformed

    private void whoDoes403bBelongtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whoDoes403bBelongtoActionPerformed
        if (whoDoes403bBelongto.getSelectedItem().toString().equals("Client")) {
            belongsToClient = true;
            belongsToSpouse = false;
        } else if (whoDoes403bBelongto.getSelectedItem().toString().equals("Spouse")) {
            belongsToClient = false;
            belongsToSpouse = true;
        } else {
            belongsToClient = false;
            belongsToSpouse = false;
        }
    }//GEN-LAST:event_whoDoes403bBelongtoActionPerformed

    private void costOfLivingAdjustmentYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costOfLivingAdjustmentYesActionPerformed
        
    }//GEN-LAST:event_costOfLivingAdjustmentYesActionPerformed

    private void costOfLivingAdjustmentNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costOfLivingAdjustmentNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costOfLivingAdjustmentNoActionPerformed

    private void costOfLivingAdjustmentTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_costOfLivingAdjustmentTextFocusGained
        if (costOfLivingAdjustmentText.getText().equals("Cost of Living Adjustment")) {
            costOfLivingAdjustmentText.setText("");
            costOfLivingAdjustmentText.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_costOfLivingAdjustmentTextFocusGained

    private void costOfLivingAdjustmentTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_costOfLivingAdjustmentTextFocusLost
        if (costOfLivingAdjustmentText.getText().equals("")) {
            costOfLivingAdjustmentText.setText("Cost of Living Adjustment");
            costOfLivingAdjustmentText.setForeground(Color.GRAY);
        } else {
            try {
                costOfLivingAdjustment = Integer.parseInt(costOfLivingAdjustmentText.getText());
            } catch (NumberFormatException e) {
                PopupMessage.popupMessage("Error", "Cost of Living Adjustment");
            }
        }
    }//GEN-LAST:event_costOfLivingAdjustmentTextFocusLost
/*
    public void getPernsionInfo() {
        if (!costOfLivingAdjustmentText.getText().equals("") || !costOfLivingAdjustmentText.getText().equals(" ")) {
            costOfLivingAdjustment = costOfLivingAdjustmentText.getText();
        }
    }
    
    */
    
    //GETTERS AND SETTERS
    
    public boolean getBelongToClient() {
        return belongsToClient;
    }
    
    public boolean getBelongsToSpouse() {
        return belongsToSpouse;
    }
    
    public boolean getLumpBool() {
        return clientRecievesLumpSumBool;
    }
    
    public void setLumpBool(boolean val) {
        clientRecievesLumpSumBool = val;
    }
    
    public boolean getMonthlyBool() {
        return clientRecievesMonthlyBool;
    }
    
    public void setMonthlyBool(boolean val) {
        clientRecievesMonthlyBool = val;
    }
    
    public int getCostOfLivingAdjustment() {
        return costOfLivingAdjustment;
    }
    
    public void setCostOfLivingAdjustment(int cost) {
        costOfLivingAdjustment = cost;
    }

    public int getAmountPension() {
        return amountPension;
    }

    public void setAmountPension(int amountPension) {
        this.amountPension = amountPension;
    }

    public int getMonth() {
        return month;
    }

    public int getDay() {
        return day;
    }

    public int getYear() {
        return year;
    }

    public void setMonth(int month) {
        this.month = month;
    }

    public void setDay(int day) {
        this.day = day;
    }

    public void setYear(int year) {
        this.year = year;
    }
    
    
    
    @Override
    public boolean getExtraPanel() {
        return extraPanel;
    }
    
    @Override 
    public String getPanelName() {
        return panelName;
    }
    
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Adjustment;
    private javax.swing.JPanel AdjustmentPanel;
    private javax.swing.JPanel BothOrOnePanel;
    private javax.swing.JPanel BothPanel;
    private javax.swing.JPanel NoAdjustment;
    private javax.swing.JPanel OnePanel;
    private javax.swing.JRadioButton additionalPanelsNo;
    private javax.swing.JRadioButton additionalPanelsNo1;
    private javax.swing.JRadioButton additionalPanelsNo2;
    private javax.swing.JRadioButton additionalPanelsYes;
    private javax.swing.JRadioButton additionalPanelsYes1;
    private javax.swing.JRadioButton additionalPanelsYes2;
    public javax.swing.JTextField amountText;
    private javax.swing.JRadioButton clientRecievesLMonthly;
    private javax.swing.JRadioButton clientRecievesLumpSum;
    private javax.swing.JRadioButton costOfLivingAdjustmentNo;
    public javax.swing.JTextField costOfLivingAdjustmentText;
    private javax.swing.JRadioButton costOfLivingAdjustmentYes;
    public javax.swing.JTextField dayAsOf403b;
    private javax.swing.JLabel jLabel141;
    private javax.swing.JLabel jLabel149;
    private javax.swing.JLabel jLabel150;
    private javax.swing.JLabel jLabel151;
    private javax.swing.JLabel jLabel152;
    private javax.swing.JLabel jLabel153;
    private javax.swing.JLabel jLabel234;
    private javax.swing.JLabel jLabel235;
    private javax.swing.JLabel jLabel236;
    private javax.swing.JLabel jLabel237;
    private javax.swing.JLabel jLabel238;
    public javax.swing.JTextField monthAsOf403b;
    private javax.swing.JComboBox<String> whoDoes403bBelongto;
    private javax.swing.JComboBox<String> whoDoesPensionBelongTo;
    public javax.swing.JTextField yearAsOf403b;
    // End of variables declaration//GEN-END:variables
}
