/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package voyagefinancial;

import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;

/**
 *
 * @author TannerLuke
 */
public class RetirementPlansPanel extends javax.swing.JPanel {

    
    public boolean clientHasPension = false;
    public boolean clientHasSocialSecurity = false;
    public boolean clientHas401K = false;
    public boolean clientHas403B = false;
    public boolean clientHas457 = false;
    public boolean clientHasIRA = false;
    public boolean clientHasSimpleIRA = false;
    public boolean clientHasSEP = false;
    public boolean clientHasNonRetirementInvestmentAccount = false;
    public boolean clientHasAnnuities = false;
    public boolean clientHasCDs = false;
    public boolean clientHasChecking = false;
    public boolean clientHasSavings = false;
    public boolean clientHasDefferedComp = false;
    public boolean clientHasHSA = false;
    public boolean clientHasFlexibleSpending = false;
    public boolean clientHasOptionsGrants = false;
    
    
    
    
  
    /**
     * Creates new form RetirementPlansPanel
     */
    public RetirementPlansPanel() {
        initComponents();
        
        Dimension size = new Dimension(this.getWidth(), this.getHeight());
        
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        retirementPlansPanel = new javax.swing.JPanel();
        jLabel139 = new javax.swing.JLabel();
        clientPensionRadio = new javax.swing.JRadioButton();
        client401KRadio = new javax.swing.JRadioButton();
        client403BRadio = new javax.swing.JRadioButton();
        clientSimpleIRARadio = new javax.swing.JRadioButton();
        clientSEPRadio = new javax.swing.JRadioButton();
        clientDefferedCompRadio = new javax.swing.JRadioButton();
        clientHSARadio = new javax.swing.JRadioButton();
        clientFlexibleSpendingRadio = new javax.swing.JRadioButton();
        jLabel140 = new javax.swing.JLabel();
        clientSocialSecurityRadio = new javax.swing.JRadioButton();
        client457Radio = new javax.swing.JRadioButton();
        clientIRARadio = new javax.swing.JRadioButton();
        clientNonRetirementInvestmentAccountRadio = new javax.swing.JRadioButton();
        clientAnnuitiesRadio = new javax.swing.JRadioButton();
        clientCDsRadio = new javax.swing.JRadioButton();
        clientCheckingRadio = new javax.swing.JRadioButton();
        clientOptionsGrantsRadio = new javax.swing.JRadioButton();
        clientSavingsRadio = new javax.swing.JRadioButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        retirementPlansPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel139.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        jLabel139.setText("Select all that apply");
        retirementPlansPanel.add(jLabel139, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, -1, 30));

        clientPensionRadio.setText("Pension");
        clientPensionRadio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                clientPensionRadioStateChanged(evt);
            }
        });
        retirementPlansPanel.add(clientPensionRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, 30));

        client401KRadio.setText("401K");
        client401KRadio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                client401KRadioStateChanged(evt);
            }
        });
        retirementPlansPanel.add(client401KRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, -1, 30));

        client403BRadio.setText("403B");
        client403BRadio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                client403BRadioStateChanged(evt);
            }
        });
        retirementPlansPanel.add(client403BRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, -1, 30));

        clientSimpleIRARadio.setText("Simple IRA");
        clientSimpleIRARadio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                clientSimpleIRARadioStateChanged(evt);
            }
        });
        retirementPlansPanel.add(clientSimpleIRARadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 180, -1, 30));

        clientSEPRadio.setText("SEP");
        clientSEPRadio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                clientSEPRadioStateChanged(evt);
            }
        });
        retirementPlansPanel.add(clientSEPRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, 30));

        clientDefferedCompRadio.setText("Deffered Comp");
        clientDefferedCompRadio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                clientDefferedCompRadioStateChanged(evt);
            }
        });
        retirementPlansPanel.add(clientDefferedCompRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, -1, 30));

        clientHSARadio.setText("HSA");
        clientHSARadio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                clientHSARadioStateChanged(evt);
            }
        });
        retirementPlansPanel.add(clientHSARadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, -1, 30));

        clientFlexibleSpendingRadio.setText("Flexible Spending");
        clientFlexibleSpendingRadio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                clientFlexibleSpendingRadioStateChanged(evt);
            }
        });
        retirementPlansPanel.add(clientFlexibleSpendingRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, -1, 30));

        jLabel140.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel140.setText("Retirement Plans");
        retirementPlansPanel.add(jLabel140, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 280, 40));

        clientSocialSecurityRadio.setText("Social Security");
        clientSocialSecurityRadio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                clientSocialSecurityRadioStateChanged(evt);
            }
        });
        retirementPlansPanel.add(clientSocialSecurityRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, 30));

        client457Radio.setText("457");
        client457Radio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                client457RadioStateChanged(evt);
            }
        });
        retirementPlansPanel.add(client457Radio, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, -1, 30));

        clientIRARadio.setText("IRA");
        clientIRARadio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                clientIRARadioStateChanged(evt);
            }
        });
        retirementPlansPanel.add(clientIRARadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 180, -1, 30));

        clientNonRetirementInvestmentAccountRadio.setText("Non-Retirement Investment Account");
        clientNonRetirementInvestmentAccountRadio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                clientNonRetirementInvestmentAccountRadioStateChanged(evt);
            }
        });
        retirementPlansPanel.add(clientNonRetirementInvestmentAccountRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, -1, 30));

        clientAnnuitiesRadio.setText("Annuities");
        clientAnnuitiesRadio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                clientAnnuitiesRadioStateChanged(evt);
            }
        });
        retirementPlansPanel.add(clientAnnuitiesRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, -1, 30));

        clientCDsRadio.setText("CDs");
        clientCDsRadio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                clientCDsRadioStateChanged(evt);
            }
        });
        retirementPlansPanel.add(clientCDsRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, -1, 30));

        clientCheckingRadio.setText("Checking");
        clientCheckingRadio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                clientCheckingRadioStateChanged(evt);
            }
        });
        retirementPlansPanel.add(clientCheckingRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 260, -1, 30));

        clientOptionsGrantsRadio.setText("Options/Grants");
        clientOptionsGrantsRadio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                clientOptionsGrantsRadioStateChanged(evt);
            }
        });
        retirementPlansPanel.add(clientOptionsGrantsRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 340, -1, 30));

        clientSavingsRadio.setText("Savings");
        clientSavingsRadio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                clientSavingsRadioStateChanged(evt);
            }
        });
        retirementPlansPanel.add(clientSavingsRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 260, -1, 30));

        add(retirementPlansPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 1070, 470));
    }// </editor-fold>//GEN-END:initComponents

    
    public Component getCurrentComponent(Container parent) {
        Component comp = null;
        int n = parent.getComponentCount();
        for (int i = 0 ; i < n ; i++) {
             comp = parent.getComponent(i);
            if (comp.isVisible()) {
                return comp;
            }
        }
        return comp;
    }
    
    public Component getNextComponent(Container parent) {
        int n = parent.getComponentCount();
        for (int i = 0 ; i < n ; i++) {
            Component comp = parent.getComponent(i);
            if (comp.isVisible()) {
                int currentCard = (i + 1) % n;
                comp = parent.getComponent(currentCard);
                return comp;
            }
        }

        return null;
    }
    
    public Component getPreviousComponent(Container parent) {
       int  n = parent.getComponentCount();
        for (int i = 0 ; i < n ; i++) {
            Component comp = parent.getComponent(i);
           
            if (comp.isVisible()) {
                int currentCard = ((i > 0) ? i-1 : n-1);
                comp = parent.getComponent(currentCard);
                return comp;
            }

        }
        return null;
    }
    
    
    public String getCurrentComponentShow(Container parent) {
        String PanelName = null;
        Component comp = null;
        int n = parent.getComponentCount();
        for (int i = 0 ; i < n ; i++) {
             comp = parent.getComponent(i);
            if (comp.isVisible()) {
               PanelName=comp.getName();
                return PanelName;
            }
        }
        return PanelName;
    }
    
    
    
    
    
    
    
    private void clientPensionRadioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_clientPensionRadioStateChanged
        if (clientPensionRadio.isSelected()) {
            clientHasPension = true;

        } else {
            clientHasPension = false;
        }
    }//GEN-LAST:event_clientPensionRadioStateChanged

    private void client401KRadioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_client401KRadioStateChanged
        if (client401KRadio.isSelected()) {
            clientHas401K = true;
        } else {
            clientHas401K = false;
        }
    }//GEN-LAST:event_client401KRadioStateChanged

    private void client403BRadioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_client403BRadioStateChanged
        if (client403BRadio.isSelected()) {
            clientHas403B = true;

        } else {
            clientHas403B = false;
        }
    }//GEN-LAST:event_client403BRadioStateChanged

    private void clientSimpleIRARadioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_clientSimpleIRARadioStateChanged
        if (clientSimpleIRARadio.isSelected()) {
            clientHasSimpleIRA = true;
        } else {
            clientHasSimpleIRA = false;
        }
    }//GEN-LAST:event_clientSimpleIRARadioStateChanged

    private void clientSEPRadioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_clientSEPRadioStateChanged
        if (clientSEPRadio.isSelected()) {
            clientHasSEP = true;

        } else {
            clientHasSEP = false;
        }
    }//GEN-LAST:event_clientSEPRadioStateChanged

    private void clientDefferedCompRadioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_clientDefferedCompRadioStateChanged
        if (clientDefferedCompRadio.isSelected()) {
            clientHasDefferedComp = true;

        } else {
            clientHasDefferedComp = false;
        }
    }//GEN-LAST:event_clientDefferedCompRadioStateChanged

    private void clientHSARadioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_clientHSARadioStateChanged
        if (clientHSARadio.isSelected()) {
            clientHasHSA = true;
        } else {
            clientHasHSA = false;
        }
    }//GEN-LAST:event_clientHSARadioStateChanged

    private void clientFlexibleSpendingRadioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_clientFlexibleSpendingRadioStateChanged
        if (clientFlexibleSpendingRadio.isSelected()) {
            clientHasFlexibleSpending = true;

        } else {
            clientHasFlexibleSpending = false;
        }
    }//GEN-LAST:event_clientFlexibleSpendingRadioStateChanged

    private void clientSocialSecurityRadioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_clientSocialSecurityRadioStateChanged
        if (clientSocialSecurityRadio.isSelected()) {
            clientHasSocialSecurity = true;
        } else {
            clientHasSocialSecurity = false;
        }
    }//GEN-LAST:event_clientSocialSecurityRadioStateChanged

    private void client457RadioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_client457RadioStateChanged
        if (client457Radio.isSelected()) {
            clientHas457 = true;
        } else {
            clientHas457 = false;

        }
    }//GEN-LAST:event_client457RadioStateChanged

    private void clientIRARadioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_clientIRARadioStateChanged
        if (clientIRARadio.isSelected()) {
            clientHasIRA = true;
        } else {
            clientHasIRA = false;
        }
    }//GEN-LAST:event_clientIRARadioStateChanged

    private void clientNonRetirementInvestmentAccountRadioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_clientNonRetirementInvestmentAccountRadioStateChanged
        if (clientNonRetirementInvestmentAccountRadio.isSelected()) {
            clientHasNonRetirementInvestmentAccount = true;

        } else {
            clientHasNonRetirementInvestmentAccount = false;
        }
    }//GEN-LAST:event_clientNonRetirementInvestmentAccountRadioStateChanged

    private void clientAnnuitiesRadioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_clientAnnuitiesRadioStateChanged
        if (clientAnnuitiesRadio.isSelected()) {
            clientHasAnnuities = true;

        } else {
            clientHasAnnuities = false;
        }
    }//GEN-LAST:event_clientAnnuitiesRadioStateChanged

    private void clientCDsRadioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_clientCDsRadioStateChanged
        if (clientCDsRadio.isSelected()) {
            clientHasCDs = true;
        } else {
            clientHasCDs = false;
        }
    }//GEN-LAST:event_clientCDsRadioStateChanged

    private void clientCheckingRadioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_clientCheckingRadioStateChanged
        if (clientCheckingRadio.isSelected()) {
            clientHasChecking = true;
        } else {
            clientHasChecking = false;
        }
    }//GEN-LAST:event_clientCheckingRadioStateChanged

    private void clientOptionsGrantsRadioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_clientOptionsGrantsRadioStateChanged
        if (clientOptionsGrantsRadio.isSelected()) {
            clientHasOptionsGrants = true;
        } else {
            clientHasOptionsGrants = false;
        }
    }//GEN-LAST:event_clientOptionsGrantsRadioStateChanged

    private void clientSavingsRadioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_clientSavingsRadioStateChanged
        if (clientSavingsRadio.isSelected()) {
            clientHasSavings = true;
        } else {
            clientHasSavings = false;
        }
    }//GEN-LAST:event_clientSavingsRadioStateChanged

    
    
    //GETTERS
    
    public boolean getHasPension() {
        return clientHasPension;
    }
    
    public boolean getHasSocialSecurity() {
        return clientHasSocialSecurity;
    }
    
    public boolean getHas401k() {
        return clientHas401K;
    }
    
    public boolean getHas403b() {
        return clientHas403B;
    }
    
    public boolean getHas457() {
        return clientHas457;
    }
    
    public boolean getHasIra() {
        return clientHasIRA;
    }
    
    public boolean getHasSimpleIra() {
        return clientHasSimpleIRA;
    }
    
    public boolean getHasSep() {
        return clientHasSEP;
    }
    
    public boolean getNonRetirementInvestmentAccount() {
        return clientHasNonRetirementInvestmentAccount;
    }
    
    public boolean getHasAnnuities() {
        return clientHasAnnuities;
    }
    
    public boolean getHasCds() {
        return clientHasCDs;
    }
    
    public boolean getHasChecking() {
        return clientHasChecking;
    }
    
    public boolean getHasSavings() {
        return clientHasSavings;
    }
    
    public boolean getHasDefferedComp() {
        return clientHasDefferedComp;
    }
    
    public boolean getHasHsa() {
        return clientHasHSA;
    }
    
    public boolean getHasFlexibleSoending() {
        return clientHasFlexibleSpending;
    }
    
    public boolean getHasOptionsGrants() {
        return clientHasOptionsGrants;
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton client401KRadio;
    private javax.swing.JRadioButton client403BRadio;
    private javax.swing.JRadioButton client457Radio;
    private javax.swing.JRadioButton clientAnnuitiesRadio;
    private javax.swing.JRadioButton clientCDsRadio;
    private javax.swing.JRadioButton clientCheckingRadio;
    private javax.swing.JRadioButton clientDefferedCompRadio;
    private javax.swing.JRadioButton clientFlexibleSpendingRadio;
    private javax.swing.JRadioButton clientHSARadio;
    private javax.swing.JRadioButton clientIRARadio;
    private javax.swing.JRadioButton clientNonRetirementInvestmentAccountRadio;
    private javax.swing.JRadioButton clientOptionsGrantsRadio;
    private javax.swing.JRadioButton clientPensionRadio;
    private javax.swing.JRadioButton clientSEPRadio;
    private javax.swing.JRadioButton clientSavingsRadio;
    private javax.swing.JRadioButton clientSimpleIRARadio;
    private javax.swing.JRadioButton clientSocialSecurityRadio;
    private javax.swing.JLabel jLabel139;
    private javax.swing.JLabel jLabel140;
    private javax.swing.JPanel retirementPlansPanel;
    // End of variables declaration//GEN-END:variables
}
